# Generated by Django 4.2.2 on 2023-06-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=20)),
                ('prod_quan', models.IntegerField()),
                ('del_date', models.DateField()),
                ('del_address', models.CharField(max_length=20)),
                ('payment_mode', models.CharField(max_length=20)),
            ],
        ),
    ]
